### ISSUE TITLE
Simplify package design for label reading

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echoregions#88]
The design of the label reading components contains the scaffolding that is too cumbersome for the couple simple geometries we are dealing with (polygons and lines). Let's simply the design to make reading labels into objects more straightforward.

**Comment by ctuguinay** [comment]
@leewujung Which label reading components are you referring to? I am a bit lost as to what you mean by scaffolding in this context.

**Comment by leewujung** [comment]
oh sorry, should make it more explicit. Label reading meaning to read EVR or EVL files. Scaffolding is the double layers of objects initiation needed to read these files.

**Comment by ctuguinay** [comment]
Oh, I see. Simplifying seems like a lot of changes need to happen in the convert modules. Let's make sure to talk about this in-depth during tomorrow's meeting.

**Comment by leewujung** [comment]
Yep, it would be quite a bit of change, but I think it may be easiest to just build it from ground up by grabbing the necessary components, instead of trying to modify from the existing structure. Let's definitely talk about this tomorrow!

**Comment by ctuguinay** [comment]
I'll add a few tasks needed to complete this task:
- [ ] For `parse_evr`: Do enough refactoring and rearranging/removing of functions so that the inner function `parse_file(evr_name)` is only called once.
- [ ] For `parse_evl`: Do enough refactoring and rearranging/removing of functions so that the inner function `parse_file(evl_name)` is only called once.

**Comment by ctuguinay** [comment]
This will be done in the refactoring, since this heavily coincides with what refactoring is meant to do.
